- hosts: hosts
  gather_facts: yes
  become: yes

  tasks:
  - name: Echo the Date to a tmp file
    shell: echo  "`date`"> /tmp/date
    
  - name: List files a tmp folder
    shell: ls -la /tmp/ > /tmp/list_files
